/**
 * Types aligned with Postgres table `registro_acciones`.
 * Convention: camelCase in TS / snake_case in SQL — mapping at API layer.
 */

export type Status = 'Pending' | 'In progress' | 'Completed' | 'On hold' | 'Cancelled';
export type Priority = 'High' | 'Medium' | 'Low';

export interface Action {
  id: number;
  hotelProperty: string;           // hotel_propiedad
  hotelId: number | null;          // hotel_id
  projectId: number | null;        // id_proyecto
  subProjectId: number | null;     // sub_id_proyecto
  project: string;                 // proyecto
  area: string;                    // area
  actionTitle: string;             // titulo_accion
  contextDescription: string;      // descripcion_contexto
  owner: string;                   // responsable
  status: Status;                  // estatus
  startDate: string;               // fecha_inicio (YYYY-MM-DD)
  endDate: string;                 // fecha_fin (YYYY-MM-DD)
  investmentUsd: number;           // inversion_usd
  expectedReturnUsd: number;       // retorno_esperado_usd
  roiPct: number | null;           // roi_pct (precomputed in DB)
  startMonth: number | null;       // mes_inicio (1-12)
  endMonth: number | null;         // mes_fin (1-12)
  durationDays: number | null;     // duracion_dias
  priority: Priority;              // prioridad
  kpiMetric: string;               // kpi_metrica
  notes: string;                   // notas_comentarios
}

export const AREA_COLORS: Record<string, string> = {
  'Marketing': '#00AFAD',
  'Operations': '#3B82F6',
  'Maintenance': '#F59E0B',
  'Technology': '#8B5CF6',
  'Revenue': '#10B981',
  'HR': '#EC4899',
  'F&B': '#F97316',
  'Sales': '#172951',
  'PR / Communications': '#14B8A6',
  'Other': '#9CA3AF',
};

export const STATUS_COLORS: Record<Status, string> = {
  'Completed': '#10B981',
  'In progress': '#00AFAD',
  'Pending': '#F59E0B',
  'On hold': '#9CA3AF',
  'Cancelled': '#EF4444',
};

export const PRIORITY_COLORS: Record<Priority, string> = {
  'High': '#EF4444',
  'Medium': '#F59E0B',
  'Low': '#10B981',
};

export const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
export const AREAS = ['Marketing', 'Operations', 'Maintenance', 'Technology', 'Revenue', 'HR', 'F&B', 'Sales', 'PR / Communications', 'Other'];
export const STATUS_LIST: Status[] = ['Pending', 'In progress', 'Completed', 'On hold', 'Cancelled'];
export const PRIORITIES: Priority[] = ['High', 'Medium', 'Low'];

// NOTE: Temporary hard-coded snapshot provided by Ops. Replace with a SQL-backed
// fetch once `registro_acciones` is wired up. Dates parsed from the source
// sheet (mixed D/M and M/D formats) using startMonth/endMonth as ground truth.
export const SEED_ACTIONS: Action[] = [
  // ── Waldorf Astoria Costa Rica (hotelId 392) ─────────────────
  {
    id: 1, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 1, subProjectId: 1,
    project: 'Guest view urgent actions', area: 'Operations',
    actionTitle: 'Guest-facing urgent actions',
    contextDescription: 'Implementación de acciones prioritarias visibles al huésped, con enfoque en uniformes y estándares de presentación',
    owner: 'GM + RH + Head Dept', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-05-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 5, durationDays: 30,
    priority: 'High', kpiMetric: '', notes: 'Prioridad en A&B y FOH',
  },
  {
    id: 2, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 2, subProjectId: 1,
    project: 'Corrective maintenance', area: 'Operations',
    actionTitle: 'Guest-facing maintenance',
    contextDescription: 'Ejecución de mantenimiento correctivo en áreas críticas de cara al huésped',
    owner: 'GM + Maintenance Director', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-05-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 5, durationDays: 30,
    priority: 'High', kpiMetric: '', notes: 'Validar contra PDF',
  },
  {
    id: 3, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 2, subProjectId: 2,
    project: 'Corrective maintenance', area: 'Operations',
    actionTitle: 'Landscaping improvements',
    contextDescription: 'Intervención en áreas de jardinería para mejorar la experiencia visual del huésped',
    owner: 'Maintenance Director', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-05-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 5, durationDays: 30,
    priority: 'Medium', kpiMetric: '', notes: 'Validar contra PDF',
  },
  {
    id: 4, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 3, subProjectId: 1,
    project: 'Staff training', area: 'Operations',
    actionTitle: 'Strengthen operational discipline (OJT)',
    contextDescription: 'Refuerzo de disciplina operativa mediante supervisión en piso y ejecución estructurada de OJT',
    owner: 'GM + Head Departments + Training Mng', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-05-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 5, durationDays: 30,
    priority: 'High', kpiMetric: '', notes: 'Enfocado en FO, F&B, Bell y HK',
  },
  {
    id: 5, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 4, subProjectId: 1,
    project: 'F&B Strategy', area: 'F&B',
    actionTitle: 'F&B Enhancements',
    contextDescription: 'Implementación de iniciativas de bajo costo para mejorar experiencia del huésped en F&B',
    owner: 'GM + F&B', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-06-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 6, durationDays: 61,
    priority: 'High', kpiMetric: '', notes: 'Plan por outlet requerido',
  },
  {
    id: 6, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 4, subProjectId: 2,
    project: 'F&B Strategy', area: 'F&B',
    actionTitle: 'Optimización de ambientación',
    contextDescription: 'Mejora de iluminación, música y decoración para elevar experiencia en puntos de consumo',
    owner: 'GM + F&B', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-06-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 6, durationDays: 61,
    priority: 'High', kpiMetric: '', notes: 'Plan por outlet requerido',
  },
  {
    id: 7, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 4, subProjectId: 3,
    project: 'F&B Strategy', area: 'F&B',
    actionTitle: 'Optimización layout y flujo',
    contextDescription: 'Rediseño de layout operativo para mejorar flujo y eficiencia en servicio',
    owner: 'GM + F&B', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-06-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 6, durationDays: 61,
    priority: 'High', kpiMetric: '', notes: 'Plan por outlet requerido',
  },
  {
    id: 8, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 5, subProjectId: 1,
    project: 'Service Culture', area: 'HR',
    actionTitle: 'Structured OJT',
    contextDescription: 'Implementación de programa estructurado de entrenamiento para fortalecer servicio',
    owner: 'GM + RH + Head Dept', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-05-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 5, durationDays: 30,
    priority: 'High', kpiMetric: '', notes: 'Enfocado en FOH',
  },
  {
    id: 9, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 4, subProjectId: 4,
    project: 'F&B Strategy', area: 'Other',
    actionTitle: 'Cross-department F&B promotion',
    contextDescription: 'Impulso de promoción interna para incrementar captura de demanda en F&B',
    owner: 'GM + Head Departments', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-05-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 5, durationDays: 30,
    priority: 'High', kpiMetric: '', notes: 'Requiere alineación comercial interna',
  },
  {
    id: 10, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 6, subProjectId: 1,
    project: 'Staffing', area: 'HR',
    actionTitle: 'Staffing ratios by occupancy',
    contextDescription: 'Alineación de staffing a niveles de ocupación para optimizar eficiencia operativa',
    owner: 'GM + RH', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-05-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 5, durationDays: 30,
    priority: 'High', kpiMetric: '', notes: 'Seguimiento RH con GM y Finanzas',
  },
  {
    id: 11, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 4, subProjectId: 5,
    project: 'F&B Strategy', area: 'F&B',
    actionTitle: 'Menu & offerings strategy',
    contextDescription: 'Optimización de oferta gastronómica mediante menu engineering',
    owner: 'GM + F&B Director + Echeff', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-06-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 6, durationDays: 61,
    priority: 'Medium', kpiMetric: '', notes: 'Plan por outlet requerido',
  },
  {
    id: 12, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 7, subProjectId: 1,
    project: 'RRHH', area: 'HR',
    actionTitle: 'Brand & service standards',
    contextDescription: 'Implementación de programas de entrenamiento Waldorf Astoria en español e inglés',
    owner: 'GM + RH + F&B', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-05-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 5, durationDays: 30,
    priority: 'High', kpiMetric: '', notes: 'Seguimiento RH',
  },
  {
    id: 13, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 8, subProjectId: 1,
    project: 'Beach Experience', area: 'Operations',
    actionTitle: 'Beach experience enhancement',
    contextDescription: 'Desarrollo y ejecución de experiencia diferenciada en área de playa',
    owner: 'GM', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-06-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 6, durationDays: 61,
    priority: 'High', kpiMetric: '', notes: 'Definir concepto y ejecución',
  },
  {
    id: 14, hotelProperty: 'Waldorf Astoria Costa Rica', hotelId: 392, projectId: 9, subProjectId: 1,
    project: 'Forbes certification', area: 'Operations',
    actionTitle: 'Forbes training',
    contextDescription: 'Reprogramación de entrenamiento en estándares Forbes, sujeto a decisión del nuevo GM',
    owner: 'GM + HR', status: 'Pending',
    startDate: '2026-04-20', endDate: '2026-05-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 5, durationDays: 30,
    priority: 'Medium', kpiMetric: '', notes: 'Presupuesto $36K reservado para mayo',
  },

  // ── Hacienda del Mar Los Cabos (hotelId 766) ─────────────────
  {
    id: 15, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 10, subProjectId: 1,
    project: 'Actividad Ritual de Llegada', area: 'Operations',
    actionTitle: 'Establecer ritual que cree un vínculo con el resort desde la llegada del huésped',
    contextDescription: 'Antes de hacer registro en el resort, se invitará a los huéspedes a ser parte de un ritual para dejar huella en haciend del mar. Se elaborará una pared movible donde los huéspedes amarrarán un lazo creando un vínculo especial con la propiedad. Actividad Incluida',
    owner: 'Humberto Mercado / Jorge Castañeda / Bellboys', status: 'Pending',
    startDate: '2026-05-07', endDate: '2026-06-30',
    investmentUsd: 1500, expectedReturnUsd: 0, roiPct: -100,
    startMonth: 5, endMonth: 6, durationDays: 54,
    priority: 'Medium', kpiMetric: 'Mejorar experiencia y reconocimiento de marca',
    notes: 'Inversión para empezar.\n\n--- Info GFG ---\nProyecto GFG: Brand – Programas y experiencias insignia\nTítulo GFG: Signature Arrival Ritual\nEstatus GFG: En proceso\nPrioridad GFG: Alta\nDescripción GFG: Detalles de ejecución enviados por GFG; hotel en revisión para cotización y definición de tiempos de implementación.\nNotas GFG: TBD',
  },
  {
    id: 16, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 11, subProjectId: 1,
    project: 'Actividad The Mark HDM', area: 'Operations',
    actionTitle: 'Retomar la actividad de The Mark',
    contextDescription: 'Se llevará a Cabo martes y viernes de cada semana a las 18:00 hrs. La actividad comienza en lobby bar donde se ofrecerá una bebida de bienvenida llamada "make a wish" mientras el equipo de actividades recolecta las tarjetas de los deseos para colocarlos en una caja de madera. Después de que los deseos son recolectados, se invitará a los huéspedes a la plazuela para disfrutar de un ritual de danza del venado con la quema de deseos. Actividad Incluida.',
    owner: 'Alejandro Mejía / Rubén Ávila / Jose Lazcarro / Jorge Castañeda', status: 'Pending',
    startDate: '2026-04-28', endDate: '2026-12-31',
    investmentUsd: 1000, expectedReturnUsd: 0, roiPct: -100,
    startMonth: 4, endMonth: 12, durationDays: null,
    priority: 'Medium', kpiMetric: 'Mejorar experiencia y reconocimiento de marca',
    notes: 'Inversión aproximada semanal.\n\n--- Info GFG ---\nProyecto GFG: Brand – Programas y experiencias insignia\nTítulo GFG: The Mark\nEstatus GFG: En proceso\nPrioridad GFG: Alta\nDescripción GFG: Bebida "make a wish" ya definida; pendiente definir frecuencia semanal (mínimo 2 días; propuesta Martes y Viernes). Horario sugerido 6:00 p.m. como gathering pre-cena, integrando lobby bar/terraza del santo y dinámica de deseos.\nNotas GFG: Implementación: 21 de abril.',
  },
  {
    id: 17, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 12, subProjectId: 1,
    project: 'Brand – Programas y experiencias insignia', area: 'Marketing',
    actionTitle: 'Entertainment (adultos y niños)',
    contextDescription: 'Revisión de oferta y ajustes operativos previstos para la visita de mayo.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-02-01', endDate: '2026-05-01',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 2, endMonth: 5, durationDays: 89,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 18, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 13, subProjectId: 1,
    project: 'Cartera Cuentas por Cobrar', area: 'Other',
    actionTitle: 'Control de Días de CXC',
    contextDescription: 'Se identificaron cuentas con atrasos significativos de entre 90 y 120 días. Ante ello, se dará una cobranza activa, con el objetivo de depurar la cartera y limpiar los saldos pendientes.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-06-30', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 6, endMonth: 12, durationDays: null,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 19, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 14, subProjectId: 1,
    project: 'Centros de Consumo', area: 'F&B',
    actionTitle: 'Establecer planes de acción para mejorar experiencia de comensal',
    contextDescription: 'Personalizar servicio reforzando uso del nombre del huésped, anticipar, asistir a huéspedes, entre otros. Disminuir filas y líneas de espera en pódiums de restaurante mejorando procesos de asignación de mesas. Ampliar y mejorar ajustes de reservaciones en Open Table de la mano con nuestro equipo de BOH para eficientar número de comensales por centro de consumo cada determinado lapso de tiempo.',
    owner: 'Rubén Avila / Guadalupe Olachea', status: 'In progress',
    startDate: '2026-04-01', endDate: '2026-06-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 6, durationDays: 90,
    priority: 'High', kpiMetric: 'Mejorar experiencia e indicadores de satisfacción',
    notes: 'Personalizar servicio por medio de reconocimiento de cada cliente llamandole por su nombre y recordando sus gustos, preferencias y restricciones. Ser dinamicos en el servicio para evitar esperas y tiempos de entrega.',
  },
  {
    id: 20, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 15, subProjectId: 1,
    project: 'Coctel Elite Members', area: 'Operations',
    actionTitle: 'Ofrecer coctel exclusivo para Elite Members MB',
    contextDescription: 'Los jueves de cada semana, se ofrecerá coctel con bebidas, canapés y música ambiental. A las 6PM en la terraza de Pitayitas',
    owner: 'Ruben Ávila / José Lazcarro / Alejandro Mejía / Jorge Castañeda', status: 'Pending',
    startDate: '2026-04-30', endDate: '2026-12-31',
    investmentUsd: 300, expectedReturnUsd: 0, roiPct: -100,
    startMonth: 4, endMonth: 12, durationDays: null,
    priority: 'Medium', kpiMetric: 'Mejora experiencia e indicadores de satisfacción',
    notes: 'Inversión Semanal\n\n--- Info GFG ---\nProyecto GFG: Brand – Programas y experiencias insignia\nTítulo GFG: Elite Members Cocktail\nEstatus GFG: En proceso\nPrioridad GFG: Media\nDescripción GFG: En definición de costos (vino de la casa, coctel insignia, cerveza, agua y canapés). Responsables asignados por rubro (bebidas/canapés/montaje/música). Ubicación: terraza con vista a motor lobby (piso 19).\nNotas GFG: Inicio: 23 de abril – 6:00 p.m.',
  },
  {
    id: 21, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 16, subProjectId: 1,
    project: 'Demand Gen', area: 'Revenue',
    actionTitle: 'Activación Paquete Hotel + Auto',
    contextDescription: 'Creacion de paquete con inclusión de renta de coche con TenCar Rental',
    owner: 'Andres Llatas', status: 'Completed',
    startDate: '2026-01-01', endDate: '2026-04-10',
    investmentUsd: 0, expectedReturnUsd: 128000, roiPct: null,
    startMonth: 1, endMonth: 4, durationDays: 99,
    priority: 'Medium', kpiMetric: 'Revenue generado Packages estimado (10%)',
    notes: 'Replicando paquete creado previo a conversión',
  },
  {
    id: 22, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 16, subProjectId: 2,
    project: 'Demand Gen', area: 'Revenue',
    actionTitle: 'Activación Paquete SPA Wellness',
    contextDescription: 'Creacion de paquete con inclusión de tratamiento "Sprit Nurturing" de 80-min en Cactus SPA por persona',
    owner: 'Andres Llatas / SPA', status: 'Completed',
    startDate: '2026-01-01', endDate: '2026-01-05',
    investmentUsd: 0, expectedReturnUsd: 20000, roiPct: null,
    startMonth: 1, endMonth: 1, durationDays: 4,
    priority: 'Medium', kpiMetric: 'Revenue generado Packages estimado (1%)',
    notes: 'Nuevo paquete para incentivar tratamientos en SPA',
  },
  {
    id: 23, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 16, subProjectId: 3,
    project: 'Demand Gen', area: 'Revenue',
    actionTitle: 'Activación Paquete Transportation',
    contextDescription: 'Creacion de paquete con inclusión de Transporte i/v Aeropuerto',
    owner: 'Andres Llatas / Erica Moreno', status: 'Completed',
    startDate: '2026-01-01', endDate: '2026-04-17',
    investmentUsd: 20000, expectedReturnUsd: 447700, roiPct: 2139,
    startMonth: 1, endMonth: 4, durationDays: 106,
    priority: 'High', kpiMetric: 'Revenue generado Retail estimado (10%)',
    notes: 'Replicando paquete que ofrece GFALC y HRH. Equals to Retail con MLOS4',
  },
  {
    id: 24, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 16, subProjectId: 4,
    project: 'Demand Gen', area: 'Revenue',
    actionTitle: 'Ajuste estrategia AAA + AAA Hot Deals',
    contextDescription: 'Revisión de descuentos aplicables a AAA y AAA Hot Deals para fechas de baja demanda',
    owner: 'Andres Llatas', status: 'Completed',
    startDate: '2026-03-04', endDate: '2026-03-18',
    investmentUsd: 0, expectedReturnUsd: 300000, roiPct: null,
    startMonth: 3, endMonth: 3, durationDays: 14,
    priority: 'Medium', kpiMetric: 'Incremento en demanda AAA', notes: '',
  },
  {
    id: 25, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 16, subProjectId: 5,
    project: 'Demand Gen', area: 'Revenue',
    actionTitle: 'Ajuste estrategia Explore + Explore Friends',
    contextDescription: 'Revisión de descuentos aplicables a Explore Friends para fechas de baja demanda con Marketing en Ofic Marriott CDMX. Aumento Allotment permitido para Explore próximos 90 días',
    owner: 'Andres Llatas', status: 'Completed',
    startDate: '2026-04-01', endDate: '2026-04-08',
    investmentUsd: 0, expectedReturnUsd: 190000, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 7,
    priority: 'Medium',
    kpiMetric: 'Incremento en demanda Associate Leisure y Discounts\nAumento de Bonvoy penetration',
    notes: '',
  },
  {
    id: 26, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 16, subProjectId: 6,
    project: 'Demand Gen', area: 'Revenue',
    actionTitle: 'Campaña Travel Zoo',
    contextDescription: 'Activación de campaña por Travel Zoo para incentivar fechas de necesidad',
    owner: 'Edward Burgos', status: 'In progress',
    startDate: '2026-03-17', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 80000, roiPct: null,
    startMonth: 3, endMonth: 4, durationDays: 44,
    priority: 'Medium', kpiMetric: 'Incremento en ingreso Discount',
    notes: 'Travel Zoo ha sido ayuda en fechas de necesidad para los próximos 90-120 días.\n167 Vouchers vendidos=353 RNTS- Reservado un 80% ; OTB 290 RNTS y REV $72,815',
  },
  {
    id: 27, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 16, subProjectId: 7,
    project: 'Demand Gen', area: 'Revenue',
    actionTitle: 'Activación Paquete "Descubre Los Cabos"',
    contextDescription: 'Creacion de paquete con inclusión de 2 actividades con Wild Canyon',
    owner: 'Andres Llatas / Hotel Team / Wild Canyon', status: 'On hold',
    startDate: '2026-01-01', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 128000, roiPct: null,
    startMonth: 1, endMonth: 12, durationDays: null,
    priority: 'High', kpiMetric: 'Revenue generado Packages estimado (10%)',
    notes: 'Nuevo paquete para incentivar actividades en destino. Se pone en pausa hasta lograr acuerdo de cómo se manejaría la venta y operación del paquete',
  },
  {
    id: 28, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 17, subProjectId: 1,
    project: 'Demand Gen Luminous', area: 'Sales',
    actionTitle: 'Establecer estrategias enfocadas en incremento de producción del programa Luminous',
    contextDescription: 'Luminous es el programa enfocado en agentes de viajes que reservan hoteles premium de Marriott. Como reservan tarifas retail o tarifas por arriba de los segmentos como wholesale & special corp, es importante tratar de incrementar la producción de este canal. Se contactó a la encargada del programa para revisar oportunidades de promociones y mkt para agentes de viajes. Estamos en espera de información para establecer siguientes pasos.',
    owner: 'Erica Moreno / Diana Rosales', status: 'In progress',
    startDate: '2026-04-06', endDate: '2026-04-24',
    investmentUsd: 5000, expectedReturnUsd: 50000, roiPct: 900,
    startMonth: 4, endMonth: 4, durationDays: 18,
    priority: 'High', kpiMetric: 'Incremento de producción', notes: '',
  },
  {
    id: 29, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 18, subProjectId: 1,
    project: 'Eficiencia Contable', area: 'Other',
    actionTitle: 'Estado de Resultados',
    contextDescription: 'En conjunto con la Dirección Financiera del hotel se está trabajando en la implementación de un nuevo formato de reporte de resultados, tal como se había planteado previamente. Este esquema busca ofrecer una visión más integral y precisa del desempeño, incorporando indicadores por huésped en los distintos rubros, así como una estructura de costos y gastos más clara y transparente.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-05-30', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 5, endMonth: 12, durationDays: null,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 30, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 19, subProjectId: 1,
    project: 'Eficiencia Costo de Alimentos y Bebidas', area: 'F&B',
    actionTitle: 'Costo de Alimentos y Bebidas',
    contextDescription: 'Como parte de las estrategias de optimización, se ha sugerido ajustar el costo por persona, lo que representa una reducción sin comprometer la calidad del servicio. Para lograrlo, se ha planteado una revisión detallada de la Gerencia General junto con el Chef, enfocada en la redistribución de insumos y menús y oferta actual.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-05-30', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 120000, roiPct: null,
    startMonth: 5, endMonth: 12, durationDays: null,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 31, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 20, subProjectId: 1,
    project: 'F&B Hideaway - Experiencia La Cava', area: 'F&B',
    actionTitle: 'Resaltar una experiencia única de F&B',
    contextDescription: 'Se escogió la experiencia en Cava de Santiago por ser el lugar una de las áreas con mas tradición del resort. En la cava se ofrece cena de 6 tiempos con maridaje con opción de dos seatings en mesas de dos personas o una mesa de 6 personas.',
    owner: 'José Lazcarro / Rubén Avila / Jorge Castañeda', status: 'Completed',
    startDate: '2026-04-13', endDate: '2026-04-13',
    investmentUsd: 0, expectedReturnUsd: 40000, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 0,
    priority: 'High', kpiMetric: 'Incremento de Ingreso no paquete',
    notes: '--- Info GFG ---\nProyecto GFG: Brand – Programas y experiencias insignia\nTítulo GFG: Hideaway\nEstatus GFG: En proceso\nPrioridad GFG: Alta\nDescripción GFG: Narrativa, menús y flyer promocional listos; A&B coordinando con Mantenimiento para condiciones óptimas de la cava y fortalecimiento de inventario de vinos.\nNotas GFG: Promoción para inicio 13 de abril.',
  },
  {
    id: 32, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 21, subProjectId: 1,
    project: 'Fitness Center', area: 'Operations',
    actionTitle: 'Establecer planes de acción para mejorar experiencia de huésped.',
    contextDescription: 'Capacitación de atención al cliente al personal nuevo del GYM y reforzar supervisión y capacitación con los cubreturnos y supervisores. Seguimiento con la contratación de empresa para el mantenimiento preventivo del equipo para no tener fuera de servicio ningún equipo.',
    owner: 'Jorge Castañeda / Alejandro Mejía', status: 'In progress',
    startDate: '2026-04-01', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 12, durationDays: 274,
    priority: 'Medium', kpiMetric: 'Mejorar experiencia e indicadores de satisfacción',
    notes: 'Caída en marzo; transición de liderazgo en Fitness (salida a mediados de marzo), recontratación de personal y reasignación de responsabilidad actual.',
  },
  {
    id: 33, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 22, subProjectId: 1,
    project: 'Flash Sale', area: 'Revenue',
    actionTitle: 'Campaña Semanal "Flash Sale"',
    contextDescription: 'Activación "Flash Sale" en canal directo y terceros (OTAs + Wholesaler)',
    owner: 'Andres Llatas / Edward Burgos', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-22',
    investmentUsd: 0, expectedReturnUsd: 180000, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 14,
    priority: 'High', kpiMetric: 'Incremento en ingreso Retail',
    notes: 'Flash Sale ha sido una campaña que nos ayuda en fechas de necesidad. La campaña actual tiene un TW hasta 31/10/2026.\nRevenue Generado hasta hoy = $141.7K USD (221 RNs) en canal directo. En OTAs $37.6K USD (72 RNs)',
  },
  {
    id: 34, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 23, subProjectId: 1,
    project: 'Guest Satisfaction – Seguimiento a oportunidades operativas', area: 'Operations',
    actionTitle: 'Cleanliness & Maintenance / Upkeep',
    contextDescription: 'Guía de staffing en revisión.',
    owner: 'GFGAM', status: 'Completed',
    startDate: '2026-03-01', endDate: '2026-04-13',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 3, endMonth: 4, durationDays: 43,
    priority: 'High', kpiMetric: '',
    notes: 'El hotel presentará el 13 de abril 2026 el detalle de acciones de mejora asociadas a áreas de oportunidad identificadas.',
  },
  {
    id: 35, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 23, subProjectId: 2,
    project: 'Guest Satisfaction – Seguimiento a oportunidades operativas', area: 'F&B',
    actionTitle: 'F&B',
    contextDescription: 'Ante caída y mayor negatividad en METAs, se trabaja en simplificación de menús en algunos outlets, amenidad por espera, estrategia de reservaciones y uso de pagers; plan integral en seguimiento.',
    owner: 'GFGAM', status: 'Completed',
    startDate: '2026-03-01', endDate: '2026-04-13',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 3, endMonth: 4, durationDays: 43,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 36, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 23, subProjectId: 3,
    project: 'Guest Satisfaction – Seguimiento a oportunidades operativas', area: 'Operations',
    actionTitle: 'Fitness Center & Spa',
    contextDescription: 'Caída en marzo; transición de liderazgo en Fitness (salida a mediados de marzo), recontratación de personal y reasignación de responsabilidad actual.',
    owner: 'GFGAM', status: 'Completed',
    startDate: '2026-03-01', endDate: '2026-04-13',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 3, endMonth: 4, durationDays: 43,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 37, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 23, subProjectId: 4,
    project: 'Guest Satisfaction – Seguimiento a oportunidades operativas', area: 'Operations',
    actionTitle: 'Spa',
    contextDescription: 'Actualización de credenciales de terapeutas; falla de bomba en hot plunge; retapizado de tumbonas; apertura de cabana de playa prevista para finales de mes.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-03-01', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 3, endMonth: 4, durationDays: 60,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 38, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 23, subProjectId: 5,
    project: 'Guest Satisfaction – Seguimiento a oportunidades operativas', area: 'Operations',
    actionTitle: 'Staff Service / Sunbeds / Condición del producto',
    contextDescription: 'Temas frecuentes en METAs: compra de 200 camastros y 125 sombrillas (entrega junio); 4,000 toallas de alberca (mitad recibida); instalación de 3 balinesas adicionales en Tortuga (total 8 en playa y 5 en alberca); entrenamiento de staff previsto para temporada baja.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-03-01', endDate: '2026-06-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 3, endMonth: 6, durationDays: 121,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 39, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 24, subProjectId: 1,
    project: 'HWS – Diferenciación Hotel vs Club y digital hygiene', area: 'Technology',
    actionTitle: 'METAs',
    contextDescription: 'Actualización de naming completada en Booking.com, Google, TripAdvisor y Expedia.',
    owner: 'GFGAM', status: 'Completed',
    startDate: '2026-02-01', endDate: '2026-04-20',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 2, endMonth: 4, durationDays: 78,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 40, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 24, subProjectId: 2,
    project: 'HWS – Diferenciación Hotel vs Club y digital hygiene', area: 'Technology',
    actionTitle: 'Hotel App',
    contextDescription: 'Contrato firmado; fecha objetivo de disponibilidad mediados de mayo.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-02-01', endDate: '2026-05-01',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 2, endMonth: 5, durationDays: 89,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 41, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 24, subProjectId: 3,
    project: 'HWS – Diferenciación Hotel vs Club y digital hygiene', area: 'Technology',
    actionTitle: 'Naming oficial en motores de búsqueda',
    contextDescription: 'Configuración en proceso para estandarizar "Hacienda del Mar Los Cabos, An Autograph Collection All-Inclusive Resort" y "The Club at Hacienda del Mar"; se identificaron variaciones por origen geográfico de búsqueda.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-02-01', endDate: '2026-05-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 2, endMonth: 5, durationDays: 118,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 42, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 24, subProjectId: 4,
    project: 'HWS – Diferenciación Hotel vs Club y digital hygiene', area: 'Technology',
    actionTitle: 'Separación conceptual y de canales',
    contextDescription: 'En seguimiento la definición de M.com como canal exclusivo del hotel y haciendadelmar.com.mx para The Club; revisión una vez concluida la implementación de Travel Curious.',
    owner: 'GFGAM', status: 'Pending',
    startDate: '2026-04-24', endDate: '2026-10-24',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 10, durationDays: 183,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 43, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 24, subProjectId: 5,
    project: 'HWS – Diferenciación Hotel vs Club y digital hygiene', area: 'Technology',
    actionTitle: 'Summary of Experiences (No Paquete)',
    contextDescription: 'Portafolio de experiencias no paquete diseñado para ofrecer alternativas adicionales que complementan la estancia.',
    owner: 'GFGAM', status: 'Pending',
    startDate: '2026-04-24', endDate: '2026-10-24',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 10, durationDays: 183,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 44, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 24, subProjectId: 6,
    project: 'HWS – Diferenciación Hotel vs Club y digital hygiene', area: 'Technology',
    actionTitle: 'Travel Curious',
    contextDescription: 'Implementación en M.com y H.com.mx para la reserva de actividades y experiencias no paquete. Feedback enviado por GFG (semana del 20/abril) y despliegue esperado al cierre de semana, con algunos retrasos por parte del proveedor debido a temas de sistema.',
    owner: 'GFGAM', status: 'Pending',
    startDate: '2026-04-24', endDate: '2026-10-24',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 10, durationDays: 183,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 45, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 25, subProjectId: 1,
    project: 'Habitaciones', area: 'Operations',
    actionTitle: 'Mejora integral de limpieza en general de habitaciones',
    contextDescription: 'A partir de la primera semana de mayo, tendremos un supervisor capacitador, reforzando estándares y procedimientos de limpieza, los cuales serán en habitaciones directamente, iniciando por camaristas recientes, hasta llegar a las de mayor antigüedad. Será una capacitación constante todo referente a limpieza, procedimientos, estándares y servicio. Reforzaremos también capacitación de las limpiezas profundas en habitaciones. Se capacitará a surtidores, haciéndoles ver la importancia de su trabajo, en entregas a huéspedes para evitar quejas por entregar tardías a solicitudes.',
    owner: 'Jorge Castañeda / Beatriz Rojas', status: 'Pending',
    startDate: '2026-05-01', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 5, endMonth: 12, durationDays: 244,
    priority: 'Medium', kpiMetric: 'Mejorar experiencia e indicadores de satisfacción', notes: '',
  },
  {
    id: 46, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 26, subProjectId: 1,
    project: 'Hospitality Room', area: 'Operations',
    actionTitle: 'Crear un área para mejorar tiempo de espera en llegada y salida de huéspedes',
    contextDescription: 'De acuerdo a los brand standards, este es un servicio para mejorar la experiencia en tiempos de espera o un área de tranquilidad para huéspedes. Se deja como pendiente pues por el momento no se tiene un área adecuada para establecer esta experiencia. Se revisará en un futuro',
    owner: 'Jorge Castañeda', status: 'On hold',
    startDate: '2026-06-30', endDate: '2026-06-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: null, endMonth: 6, durationDays: null,
    priority: 'Medium', kpiMetric: '',
    notes: '--- Info GFG ---\nProyecto GFG: Brand – Programas y experiencias insignia\nTítulo GFG: Hospitality Room\nEstatus GFG: En proceso\nPrioridad GFG: Media\nDescripción GFG: No se cuenta con espacio dedicado; se está evaluando alternativa de experiencia de bienvenida con amenidades en lobby y una propuesta de experiencia de salida (mejora de área de poltronas en arrival lobby para espera de transportación).',
  },
  {
    id: 47, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 27, subProjectId: 1,
    project: 'Implementar actividad "The Guide & Me"', area: 'Operations',
    actionTitle: 'Incluir caminata guiada de la propiedad, por áreas que resaltan la identidad y riqueza cultural e histórica del resort.',
    contextDescription: 'Se incluirá esta actividad a la agenda de actividades semanales. Se visitarán áreas como la capilla, las fuentes, el santo de cabeza, flora endémica y otros representativos del resort. Actividad incluida.',
    owner: 'Alejandro Mejía / Jorge Castañeda', status: 'Pending',
    startDate: '2026-05-04', endDate: '2026-06-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 5, endMonth: 6, durationDays: 57,
    priority: 'Medium', kpiMetric: 'Mejorar experiencia y reconocimiento de marca',
    notes: '--- Info GFG ---\nProyecto GFG: Brand – Programas y experiencias insignia\nTítulo GFG: Guide & Me\nEstatus GFG: En proceso\nPrioridad GFG: Media\nDescripción GFG: Por ubicación del hotel, la versión original fuera de propiedad no es viable; se implementará como parte de entretenimiento. Se trabaja con Jardinería para identificar especies endémicas y desarrollar placas/narrativa (avance ~50%) para integrar recorrido por jardines dentro del tour de la propiedad. En paralelo, se solicitará descripción de "callejoneada" para validar si cumple requisitos; se definirá entre esta opción y el nuevo tour.\nNotas GFG: Fecha TBD; alternativas no paquete a revisarse durante visita de mayo.',
  },
  {
    id: 48, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 28, subProjectId: 1,
    project: 'Incremento leads Bodas', area: 'Sales',
    actionTitle: 'Establecer estrategias enfocadas en incremento de generación de leads de bodas',
    contextDescription: 'Además de promociones se necesita incrementar el exposure del hotel en los mercados principales así como con Wedding Planners locales. Se ha tenido un periodo de ajuste con la conversión de EP a AI pero es importante que la producción empiece a incrementar.',
    owner: 'Erica Moreno / Ayde Cortez', status: 'In progress',
    startDate: '2026-04-13', endDate: '2026-04-24',
    investmentUsd: 50000, expectedReturnUsd: 250000, roiPct: 400,
    startMonth: 4, endMonth: 4, durationDays: 11,
    priority: 'High', kpiMetric: 'Incremento de producción', notes: '',
  },
  {
    id: 49, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 29, subProjectId: 1,
    project: 'Ingreso No Paquete', area: 'Revenue',
    actionTitle: 'Incremento Ratio Por Persona',
    contextDescription: 'Se plantearon diversas estrategias de eficiencia de cara al comportamiento esperado del negocio en los próximos meses. El propósito es anticipar las tendencias de operación y mercado, ajustando tanto la estructura de costos para asegurar una mayor rentabilidad.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-05-15', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 5, endMonth: 12, durationDays: null,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 50, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 30, subProjectId: 1,
    project: 'NPR - Generación de Ingreso No Paquete', area: 'Revenue',
    actionTitle: 'Bali Bed Experiences (Barefoot & Sea Foam Packages)',
    contextDescription: 'Private poolside or beachfront retreats for up to four guests, featuring dedicated service and curated beverage offerings — from premium champagne to refreshing sparkling wine — for a relaxed yet elevated day by the water.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-02-01', endDate: '2026-10-24',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 2, endMonth: 10, durationDays: 265,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 51, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 30, subProjectId: 2,
    project: 'NPR - Generación de Ingreso No Paquete', area: 'Revenue',
    actionTitle: 'Roots & Terroir: Intimate Cellar Dinner (for two)',
    contextDescription: 'A six-course tasting menu in an underground wine cellar, paired with 100% Mexican wines and spirits, offering a deeply personal and immersive dining experience.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-02-01', endDate: '2026-06-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 2, endMonth: 6, durationDays: 149,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 52, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 30, subProjectId: 3,
    project: 'NPR - Generación de Ingreso No Paquete', area: 'Revenue',
    actionTitle: 'Roots & Terroir: Six Seats in the Cellar',
    contextDescription: 'A shared or private group experience for six guests, exploring Mexico\'s regional cuisine through a multi-course tasting menu with curated pairings and storytelling.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-02-01', endDate: '2026-06-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 2, endMonth: 6, durationDays: 149,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 53, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 30, subProjectId: 4,
    project: 'NPR - Generación de Ingreso No Paquete', area: 'Revenue',
    actionTitle: 'Tacos & Mezcales of the Soul',
    contextDescription: 'A guided tasting experience at Tahona featuring four signature tacos paired with artisanal mezcales and Mexican spirits, led by a mezcal expert.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-02-01', endDate: '2026-06-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 2, endMonth: 6, durationDays: 149,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 54, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 31, subProjectId: 1,
    project: 'Niveles de Staffing Por Ocupación', area: 'HR',
    actionTitle: 'Alineación Niveles Reales de Staffing',
    contextDescription: 'Tras la revisión de las líneas de staffing, se determinó que el esquema actual —basado en ajustes cada 30% de ocupación— resulta insuficiente para reflejar con precisión las necesidades operativas. Se realizará un ejercicio de ajuste cada 10% de ocupación, lo que permitirá una mayor alineación entre la demanda real y la estructura de personal. Asimismo, se identificó la necesidad de revisar el headcount en áreas críticas, particularmente en Alimentos y Bebidas y División Cuartos.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-05-15', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 5, endMonth: 12, durationDays: null,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 55, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 32, subProjectId: 1,
    project: 'Optimizacion de Costo de Nómina-Eficiencia Operativa', area: 'Operations',
    actionTitle: 'Implementación de Reforecast mensual de acuerdo a ocupacion, para optimizacion de la nómina, ajustada a la operación.',
    contextDescription: 'Ajustar la plantilla de nómina, asegurando la operación sin afectar sobrecosto, ni el nivel de servicio.',
    owner: 'CE', status: 'In progress',
    startDate: '2026-04-01', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 12, durationDays: 274,
    priority: 'High',
    kpiMetric: 'Operar con eficiencia, eliminar sobre pagos (tiempo extra, dobles, turnos, descansos trabajados, cuartos extras), productividad',
    notes: 'Eliminación de sobrepagos (20 abril, 2026 al 30 septiembre, 2026)',
  },
  {
    id: 56, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 32, subProjectId: 2,
    project: 'Optimizacion de Costo de Nómina-Eficiencia Operativa', area: 'Operations',
    actionTitle: 'Programación y ejecucion de vacaciones de acuerdo al plan anual, enfatizando en los meses de baja ocupacion (mayo a septiembre)',
    contextDescription: 'Planificar las vacaciones del staff, alineada a la proyeccion de la baja ocupación, lo que nos permitira reducir la carga operativa, optimizar la productividad y evitar acumulación de las mismas.',
    owner: 'CE', status: 'In progress',
    startDate: '2026-01-01', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 1, endMonth: 12, durationDays: 364,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 57, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 33, subProjectId: 1,
    project: 'PR Strategy', area: 'Marketing',
    actionTitle: 'Alineación next steps, contenido, necesidad demanda',
    contextDescription: 'Enviar información sobre contenido, historias, segmentos, necesidad de demanda, etc',
    owner: 'Erica Moreno', status: 'Completed',
    startDate: '2026-04-13', endDate: '2026-04-17',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 4,
    priority: 'High', kpiMetric: 'Incremento Brand Awardness',
    notes: 'Proveer toda la información importante del hotel para que la agencia elabore una estrategia de RP que nos apoye a incrementar awareness así como también apoyar en la generación de ingresos.',
  },
  {
    id: 58, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 1,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Kick-off',
    contextDescription: 'Llamada realizada el 8 de abril de 2026.',
    owner: 'GFGAM', status: 'Completed',
    startDate: '2026-04-08', endDate: '2026-04-08',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 0,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 59, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 2,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Activos visuales',
    contextDescription: '"Vote Now" co-brandeado, pack de posts para feed (mínimo 3 variaciones quincenales), pack de stories con link, 1 reel con highlights y call-to-action, firma de email para equipo interno y banner para bio de Instagram.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 22,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 60, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 3,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Base de datos de huéspedes',
    contextDescription: 'Clientes recientes y anteriores activados vía email marketing con instrucciones claras de votación.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 22,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 61, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 4,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Comunidad digital',
    contextDescription: 'Fans, seguidores y ex huéspedes activados vía redes sociales.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 22,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 62, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 5,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Email 1',
    contextDescription: 'Huéspedes recientes (24 hrs post-stay).',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 22,
    priority: 'Medium', kpiMetric: '',
    notes: 'Cada email se enviará al menos dos veces: una ronda en abril y una segunda en mayo/junio previo al cierre de votación.',
  },
  {
    id: 63, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 6,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Email 2',
    contextDescription: 'Base histórica (instrucciones paso a paso + categoría Resorts).',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 22,
    priority: 'Medium', kpiMetric: '',
    notes: 'Cada email se enviará al menos dos veces: una ronda en abril y una segunda en mayo/junio previo al cierre de votación.',
  },
  {
    id: 64, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 7,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Email 3',
    contextDescription: 'Base interna/colaboradores (cómo votar + relevancia de la nominación).',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 22,
    priority: 'Medium', kpiMetric: '',
    notes: 'Cada email se enviará al menos dos veces: una ronda en abril y una segunda en mayo/junio previo al cierre de votación.',
  },
  {
    id: 65, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 8,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Equipo interno del resort',
    contextDescription: 'Asociados y colaboradores amplificando el mensaje desde sus redes personales.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 22,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 66, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 9,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Estrategia de campaña (votación)',
    contextDescription: 'La campaña inicia esta semana y está diseñada como un esfuerzo de movilización de audiencia, más allá de contenido, con tres frentes: comunidad digital, base de datos de huéspedes y equipo interno del resort.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 22,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 67, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 10,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Immersion Trip',
    contextDescription: 'Fechas 11–14 de mayo; agenda a recibirse el 23 de abril.',
    owner: 'GFGAM', status: 'Pending',
    startDate: '2026-05-11', endDate: '2026-05-14',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 5, endMonth: 5, durationDays: 3,
    priority: 'High', kpiMetric: '', notes: '',
  },
  {
    id: 68, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 34, subProjectId: 11,
    project: 'PR – Campaña Conde Nast Traveler', area: 'PR / Communications',
    actionTitle: 'Social media (lineamientos)',
    contextDescription: 'Mensaje universal para empleados (con link directo), pin del post de nominación en páginas del resort y tagging correcto a @cntraveler en cada publicación.',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-04-08', endDate: '2026-04-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 4, durationDays: 22,
    priority: 'Medium', kpiMetric: '', notes: '',
  },
  {
    id: 69, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 35, subProjectId: 1,
    project: 'Spa', area: 'Operations',
    actionTitle: 'Reforzar protocolos de servicio para mejorar experiencia del usuario',
    contextDescription: 'Llamar al cliente por su nombre y usarlo al menos 2 veces en la conversación. Si tiene estatus Marriott Bonvoy agradecerle su fidelidad. A los Socios del Club vacacional reconocerles su fidelidad. En Cabina trabajaremos más allá del protocolo y leer la necesidad del cuerpo y enfocarse, lo cual ayudará en la recomendación del 2do servicio. Al cierre, preguntar por su experiencia, tratar de cerrar venta y si notamos que algo no está al 100% indagar para saber si hay algo más que podamos hacer por el cliente de manera significativa y emocional.',
    owner: 'Jorge Castañeda / Josselyn De La Mora', status: 'In progress',
    startDate: '2026-04-01', endDate: '2026-06-30',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 6, durationDays: 90,
    priority: 'Medium', kpiMetric: 'Mejorar experiencia e indicadores de satisfacción', notes: '',
  },
  {
    id: 70, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 36, subProjectId: 1,
    project: 'Staffing Ama de Llaves', area: 'HR',
    actionTitle: 'Estructura Camaristas y Créditos de Limpieza',
    contextDescription: 'El staffing de Camaristas está sumamente desfasado con base en los niveles de ocupación; por ello se realizó un ejercicio que permitirá tener un ahorro del mes de Mayo a Diciembre',
    owner: 'GFGAM', status: 'In progress',
    startDate: '2026-05-15', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 160000, roiPct: null,
    startMonth: 5, endMonth: 12, durationDays: null,
    priority: 'Medium', kpiMetric: '', notes: 'Ya existe un staffing propuesto',
  },
  {
    id: 71, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 37, subProjectId: 1,
    project: 'Travel Curious', area: 'Marketing',
    actionTitle: 'Lanzamiento NPRs Marriott.com/SJDHA',
    contextDescription: '',
    owner: 'Erica Moreno', status: 'In progress',
    startDate: '2026-03-16', endDate: '2026-04-21',
    investmentUsd: 5387, expectedReturnUsd: 200000, roiPct: 3613,
    startMonth: 3, endMonth: 4, durationDays: 36,
    priority: 'High', kpiMetric: 'Incremento ingreso No paquete',
    notes: 'Se mandó copy a revisión de Dirección General. No se cuenta con fotografías adecuadas por lo que se está revisando la posibilidad de un nuevo photo shooting, mientras tanto, se pudieran usar fotos de stock. Ya se solicitó cotización de fotografía a fotografo local autorizado por Marriott',
  },
  {
    id: 72, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 38, subProjectId: 1,
    project: 'Upgrade Minibar Elite Members', area: 'F&B',
    actionTitle: 'Reconocimiento a Elite Members',
    contextDescription: 'Se incluirá un snack y una bebida exclusiva para reconocer a los Elite Members de MB y agradecer su lealtad. Por el momento se están esperando muestras de los productos para decidir.',
    owner: 'Rubén Avila / Miguel Martinez / Jorge Castañeda', status: 'Pending',
    startDate: '2026-06-01', endDate: '2026-12-31',
    investmentUsd: 15, expectedReturnUsd: 0, roiPct: -100,
    startMonth: 6, endMonth: 12, durationDays: null,
    priority: 'Medium', kpiMetric: '',
    notes: 'Inversión estimada por cuarto ocupado por Elite Member\n\n--- Info GFG ---\nProyecto GFG: Brand – Programas y experiencias insignia\nTítulo GFG: Mini Bar\nEstatus GFG: En proceso\nPrioridad GFG: Media\nDescripción GFG: Propuesta de oferta adicional bajo revisión por impacto en costos.\nNotas GFG: Fecha estimada de implementación 30 de abril.',
  },
  {
    id: 73, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 39, subProjectId: 1,
    project: 'Wholesaler', area: 'Revenue',
    actionTitle: 'Conexión nuevas cuentas Wholesalers por Dingus+Omnibees',
    contextDescription: 'Buscar nuevas cuentas con demanda en Los Cabos para conectar via Dingus y Omnibees',
    owner: 'Andres Llatas / Edward Burgos / Diana Rosales', status: 'In progress',
    startDate: '2026-01-01', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 875000, roiPct: null,
    startMonth: 1, endMonth: 12, durationDays: null,
    priority: 'High', kpiMetric: 'Incremento en demanda Wholesalers',
    notes: 'Cuentas en proceso de conexión: TFN, Nuitee, Caribeo, Euromundo\nCuentas conectadas Dingus: 8\nCuentas conectadas Omnibees: 13',
  },
  {
    id: 74, hotelProperty: 'Hacienda del Mar Los Cabos', hotelId: 766, projectId: 40, subProjectId: 1,
    project: 'Áreas Públicas', area: 'Operations',
    actionTitle: 'Establecer planes de acción para mejorar experiencia de huésped.',
    contextDescription: 'Se incrementó el número de personal del equipo nocturno para realizar las limpiezas a detalle y profundidad, así como el lavado constante de áreas que no se pueden lavar durante el día por la afluencia de huéspedes. Se implementa un rol de lavado de áreas en general (Albercas, centro de consumo, villas, andadores) para dar mayor continuidad al lavado constante. Se ajustan la operación y las tareas del personal de las 5:00am para enfocarnos en andadores y elevadores limpios antes de los huéspedes empiecen a circular por las áreas.',
    owner: 'Jorge Castañeda / Daniel Pimienta', status: 'In progress',
    startDate: '2026-04-01', endDate: '2026-12-31',
    investmentUsd: 0, expectedReturnUsd: 0, roiPct: null,
    startMonth: 4, endMonth: 12, durationDays: 274,
    priority: 'Medium', kpiMetric: 'Mejorar experiencia e indicadores de satisfacción', notes: '',
  },
];

export const fmtMoney = (n: number) =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);

export const calcRoi = (inv: number, ret: number) => (inv > 0 ? Math.round(((ret - inv) / inv) * 100) : 0);

/** Returns roiPct if precomputed in DB, otherwise calculates it. */
export const getRoi = (a: Action) =>
  a.roiPct !== null && a.roiPct !== undefined ? Math.round(a.roiPct) : calcRoi(a.investmentUsd, a.expectedReturnUsd);

export const monthIdx = (date: string) => new Date(date + 'T00:00:00').getMonth();

export const fmtDate = (str: string) => {
  if (!str) return '—';
  const [y, m, d] = str.split('-');
  return `${m}/${d}/${y}`;
};
